[package]
authors = ["Tommy Lau <tommy.lhg@gmail.com>"]
name = "learn-opengl-rs"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.6.0"
glfw = "0.43.0"
