name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update brew
        run: brew update
      - name: Install assimp
        run: brew install assimp
      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --lib --verbose
      - name: Clippy
        run: |
          rustup component add clippy
          cargo clippy --all-targets
