name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Stable
        run: |
          rustup install 1.59.0
          cargo test
      - name: Clippy
        run: |
          rustup component add clippy
          cargo clippy --all-targets
  check-macos-arm:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Install target
        run: |
          rustup install 1.59.0
          rustup target add aarch64-apple-darwin
      - name: Build
        run: cargo build --target=aarch64-apple-darwin
